// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaNvJlOyoPlmV8LUbn3ZcoB23LqYGAQmE',
    appId: '1:357005393053:android:66838e2b74c5be8cb36874',
    messagingSenderId: '357005393053',
    projectId: 'chatapp-renga',
    storageBucket: 'chatapp-renga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLUKTWvPN_eTK7RenLZq1wcEcwQfF0IOY',
    appId: '1:357005393053:ios:043be3423b10a400b36874',
    messagingSenderId: '357005393053',
    projectId: 'chatapp-renga',
    storageBucket: 'chatapp-renga.firebasestorage.app',
    iosBundleId: 'com.minnya.renga',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQlHsJNmBSnBe3xcbdXUHpRt-LYERSU2Q',
    appId: '1:357005393053:web:5504778b7d5ca95ab36874',
    messagingSenderId: '357005393053',
    projectId: 'chatapp-renga',
    authDomain: 'chatapp-renga.firebaseapp.com',
    storageBucket: 'chatapp-renga.firebasestorage.app',
    measurementId: 'G-DWNZWP9CXW',
  );
}
